name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # o la rama que desees utilizar para el despliegue

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseToken: ${{ secrets.FIREBASE_TOKEN }}  # Usar el token guardado en los secretos de GitHub
          projectId: vue-chat-hyl  # Reemplaza con el ID real de tu proyecto en Firebase
